# Generated by Django 4.1.1 on 2022-10-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emaill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
